module.exports = {
	IN_RULE: "inRule",
	MERGE_RULE: "mergeRule",
	OUT_RULE: "outRule",
	BODY: "body",
	PARAMETERS: "parameters",
	NAME: "name",
	MODE: "mode",
	PROPERTIES: "properties",
	REQUIRED: "required",
	TYPE: "type",
	CAST_TO: "castTo",
	MIN: "min",
	MAX: "max",
	MATCH: "match",
	OPTIONAL: "optional",
	CLEAN: "clean",
	VALIDATE: "validate",
	DEFAULT: "default",
	RESTRICTIVE: "restrictive",
	PERMISSIVE: "permissive",
	BEFORE_MERGE: "beforeMerge",
	FUNCTION: "function",
	STRING: "string",
	NUMBER: "number",
	INTEGER: "integer",
	INT: "int",
	UNSIGNED_INTEGER: "unsigned integer",
	UINT: "uint",
	ARRAY: "array",
	OBJECT: "object",
	BOOLEAN: "boolean",
	ERRORS: {
		MISSING: "missing",
		TYPE: "type",
		RANGE: "range",
		MATCH: "match",
	},
	USER_INPUT: "userInput",
	NONE: "none",
	UNKNOWN: "unknown",
};

